package edu.sdust.insapp.utils;

import java.text.SimpleDateFormat;
import java.util.Date;

import lecho.lib.hellocharts.formatter.AxisValueFormatter;
import lecho.lib.hellocharts.model.AxisValue;

/**
 * Created by Administrator on 2017/11/3.
 */

public class MyDateFormatter implements AxisValueFormatter {

    private static MyDateFormatter myDateFormatter;

    static {
        myDateFormatter = new MyDateFormatter();
    }

    public static MyDateFormatter getInstance(){
        return myDateFormatter;
    }

    private MyDateFormatter(){};

    @Override
    public int formatValueForManualAxis(char[] formattedValue, AxisValue axisValue) {
        Date date = TimeConvert.getDateByDays((int)axisValue.getValue());
        char[] result = new SimpleDateFormat("M-d").format(date).toCharArray();
        System.arraycopy(result,0,formattedValue,formattedValue.length-result.length,result.length);


        return result.length;
    }

    @Override
    public int formatValueForAutoGeneratedAxis(char[] formattedValue, float value, int autoDecimalDigits) {
        Date date = TimeConvert.getDateByDays((int)value);
        char[] result = new SimpleDateFormat("M-d").format(date).toCharArray();
        System.arraycopy(result,0,formattedValue,formattedValue.length-result.length,result.length);
        return result.length;
    }
}
